backup-full: allow override config path via env BACKUP_CONFIG; die() provides feedback on failure

diff --git a/bin/backup-full b/bin/backup-full
--- a/bin/backup-full
+++ b/bin/backup-full
@@ -12,6 +12,7 @@
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
+die() { echo "$0: $*" >&2 ; exit 1 ; }
 logger "running backup-full for $LOGNAME"
 set -x
 
@@ -21,23 +22,32 @@ set -x
 DATEI="$( date +'%Y-%m-%d' )"
 DATEW="$( date +'%w' )"
 HOST="$( hostname )"
-[ -r "$HOME/etc/backup/config" ] && source "$HOME/etc/backup/config"
+
+BACKUP_CONFIG="${BACKUP_CONFIG:-$HOME/etc/backup/config}"
+[ -r "$BACKUP_CONFIG" ] || die "cannot read config $BACKUP_CONFIG"
+. "$BACKUP_CONFIG"
 
 # override by exporting non-default value before calling
 [ -z "$BACKUP_FULL_DIR" ] && BACKUP_FULL_DIR="$HOME/backups/full"
 [ -z "$BACKUP_ETC" ] && BACKUP_ETC="$HOME/etc/backup"
 [ -z "$BACKUP_FULL_KEEP_DAYS" ] && BACKUP_FULL_KEEP_DAYS=3
 
-[ ! -e "$BACKUP_ETC" ] && mkdir -p "$BACKUP_ETC"
-[ ! -r "$BACKUP_ETC" ] || [ ! -w "$BACKUP_ETC" ] && exit 1
+if [ ! -e "$BACKUP_ETC" ]
+then
+    mkdir -p "$BACKUP_ETC" || die "could not mkdir $BACKUP_ETC"
+fi
+[ ! -r "$BACKUP_ETC" ] || [ ! -w "$BACKUP_ETC" ] && die "bad permissions $BACKUP_ETC"
 
 # allow disabling backups by touching a file
 [ -e "$BACKUP_ETC/disable" ] || [ -e "$BACKUP_ETC/disabled" ] && exit 0
 
-[ ! -e "$BACKUP_FULL_DIR" ] && mkdir -p "$BACKUP_FULL_DIR"
-[ ! -w "$BACKUP_FULL_DIR" ] && exit 1
+if [ ! -e "$BACKUP_FULL_DIR" ]
+then
+    mkdir -p "$BACKUP_FULL_DIR" || die "could not mkdir $BACKUP_FULL_DIR"
+fi
+[ ! -w "$BACKUP_FULL_DIR" ] && die "cannot write to $BACKUP_FULL_DIR"
 
-# delete old backups 
+# delete old backups
 find "$BACKUP_FULL_DIR" -daystart -mtime +$BACKUP_FULL_KEEP_DAYS -type f -print0 | xargs -r -0 rm -f
 
 # read each line of $BACKUP_ETC/include into an array element
@@ -70,4 +80,6 @@ nice tar --create \
     --exclude-from "$BACKUP_ETC/exclude" \
     --gzip \
     ${DIRS[*]}
+SC=$? && [ $SC -eq 0 ] || die "tar --create failed with status $SC"
 
+exit 0
